### ISSUE TITLE
Manuscript resubmission checklist

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/spectratrait#64]
- [x] Convert to package (shawn)
- [x] Remove unused depends (@neo0351)
- [x] Update README - revise links and update contains and other text (@neo0351 )
- [x] Update example scripts in inst/scripts (shawn)
- [x] Update vignettes (shawn)
- [x] Add tests (all)
- [x] TEST group testing sesh, squash bugs (all)
- [x] Create internal dataset to use in an example not dependent on EcoSIS
- [x] Create additional supplemental example that sources a package dataset (shawn)
- [x] Update example script to include supplemental figure captions
...
- [x] more here
